# -*- coding: utf-8 -*-
"""Aula 1 - Imersão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfKHN_Gd3ooc4U2d-C-kTm-cKstwaAVY
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

"""DF: Apelido do arquivo

pd: Apelido que demos para a biblioteca

read.csv: Vai exibir as linhas do arquivo CSV
"""

df.head()

"""head: comando da biblioteca"""

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print("linhas: ", linhas)
print("Colunas: ", colunas)

df.columns

renomear_colunas={
    'ano_trabalho': 'ano',
    'nivel_experiencia': 'senioridade',
    'tipo_emprego': 'contrato',
    'cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_empregado': 'residencia',
    'taxa_remoto': 'remoto',
    'localizacao_empresa': 'empresa',
    'tamanho_empresa': 'tamanho_empresa'
}
df.rename(columns=renomear_colunas, inplace=True)
df.columns

df["senioridade"].value_counts()

df["contrato"].value_counts()

df["remoto"].value_counts()

df["tamanho_empresa"].value_counts()

senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

df["senioridade"] = df["senioridade"].replace(senioridade)
df["senioridade"].value_counts()

contrato = {
    'FT': 'Tempo Integral',
    'PT': 'Tempo Parcial',
    'FL': 'Frellance',
    'CT': 'Contrato'
}

df["contrato"] = df["contrato"].replace(contrato)
df["contrato"].value_counts()

tamanho_empresa = {
    'S': 'Pequena',
    'M': 'Media',
    'L': 'Grande',
}

df["tamanho_empresa"] = df["tamanho_empresa"].replace(tamanho_empresa)
df["tamanho_empresa"].value_counts()

remoto = {
    0: 'Presencial',
    50: 'Hibrido',
    100: 'Remoto',
}

df["remoto"] = df["remoto"].replace(remoto)
df["remoto"].value_counts()

df.head()

df.describe(include=object)

df.describe()